# Generated by Django 6.0.7 on 2026-07-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gioco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('piattaforma', models.CharField(choices=[('PC', 'PC'), ('PS5', 'PlayStation 5'), ('XBOX', 'Xbox Series'), ('SWITCH', 'Nintendo Switch')], default='PC', max_length=10)),
                ('stato', models.CharField(choices=[('DA_GIOCARE', 'Da giocare'), ('IN_CORSO', 'In corso'), ('FINITO', 'Finito'), ('ABBANDONATO', 'Abbandonato')], default='DA_GIOCARE', max_length=12)),
                ('ore_giocate', models.PositiveIntegerField(default=0)),
                ('voto', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('data_aggiunta', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_aggiunta'],
            },
        ),
    ]
