# Generated by Django 6.0.7 on 2026-07-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('giochi', '0002_genere_sviluppatore_gioco_generi_gioco_sviluppatore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genere',
            options={'ordering': ['nome'], 'verbose_name_plural': 'generi'},
        ),
        migrations.AlterModelOptions(
            name='gioco',
            options={'ordering': ['-data_aggiunta'], 'verbose_name_plural': 'giochi'},
        ),
        migrations.AlterModelOptions(
            name='sviluppatore',
            options={'ordering': ['nome'], 'verbose_name_plural': 'sviluppatori'},
        ),
    ]
